import { useState } from 'react';
import { motion } from 'framer-motion';

function generateAdsTxt(domain) {
  const lines = [
    `# ads.txt file for ${domain}`,
    `# Generated by AudioVerse Publisher Platform`,
    `# Last updated: ${new Date().toISOString().split('T')[0]}`,
    `#`,
    `# AudioVerse Direct`,
    `${domain}, pub-av-${Math.random().toString(36).slice(2, 10)}, DIRECT, f08c47fec0942fa0`,
    `#`,
    `# AudioVerse Reseller Partners`,
    `audioverse.ai, 1234567890, DIRECT, f08c47fec0942fa0`,
    `google.com, pub-1234567890123456, RESELLER, f08c47fec0942fa0`,
    `openx.com, 537153564, RESELLER, 6a698e2ec38604c6`,
    `rubiconproject.com, 15636, RESELLER, 0bfd66d529a55807`,
    `indexexchange.com, 189529, RESELLER, 50b1c356f2c5c8fc`,
    `appnexus.com, 3663, RESELLER, f5ab79cb980f11d1`,
    `pubmatic.com, 157097, RESELLER, 5d62403b186c2b0d`,
    `#`,
    `# Contact: publishers@audioverse.ai`,
  ];
  return lines.join('\n');
}

export default function AdsTxtGenerator() {
  const [domain, setDomain] = useState('');
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const handleGenerate = () => {
    if (!domain.trim()) return;
    const cleaned = domain.trim().replace(/^https?:\/\//, '').replace(/\/.*$/, '');
    setOutput(generateAdsTxt(cleaned));
  };

  const handleCopy = async () => {
    if (!output) return;
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* ignore */ }
  };

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ads.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <section className="px-4 lg:px-6 mb-12">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >
        <h2 className="font-display text-2xl font-bold mb-2 text-center">
          <span className="gradient-text">Ads.txt Generator</span>
        </h2>
        <p className="text-gray-400 text-sm text-center mb-8 max-w-lg mx-auto">
          Generate an IAB-compliant ads.txt file for your domain in seconds.
        </p>

        <div className="glass rounded-2xl p-6 lg:p-8 max-w-3xl mx-auto">
          {/* Domain input */}
          <div className="flex gap-3 mb-6">
            <input
              type="text"
              value={domain}
              onChange={e => setDomain(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleGenerate()}
              placeholder="yourdomain.com"
              className="flex-1 px-4 py-3 rounded-lg bg-white/[0.06] border border-white/[0.1] text-sm text-white placeholder-gray-500 focus:outline-none focus:border-primary-500/50 focus:ring-1 focus:ring-primary-500/30 transition-all"
            />
            <button
              onClick={handleGenerate}
              disabled={!domain.trim()}
              className="px-6 py-3 rounded-lg bg-primary-500 hover:bg-primary-400 disabled:opacity-40 disabled:cursor-not-allowed font-semibold text-sm transition-colors shrink-0"
            >
              Generate
            </button>
          </div>

          {/* Output */}
          {output && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              transition={{ duration: 0.3 }}
            >
              <div className="rounded-xl overflow-hidden border border-white/[0.08]">
                {/* Header */}
                <div className="flex items-center justify-between px-4 py-2.5 bg-[rgba(22,33,62,0.9)] border-b border-white/[0.06]">
                  <div className="flex items-center gap-2">
                    <div className="flex gap-1.5">
                      <div className="w-3 h-3 rounded-full bg-red-500/80" />
                      <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                      <div className="w-3 h-3 rounded-full bg-green-500/80" />
                    </div>
                    <span className="text-xs text-gray-500 ml-2 font-mono">ads.txt</span>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={handleCopy}
                      className="text-xs text-gray-500 hover:text-white transition-colors px-2 py-1 rounded hover:bg-white/10"
                    >
                      {copied ? 'Copied!' : 'Copy'}
                    </button>
                    <button
                      onClick={handleDownload}
                      className="text-xs text-gray-500 hover:text-white transition-colors px-2 py-1 rounded hover:bg-white/10"
                    >
                      Download
                    </button>
                  </div>
                </div>

                {/* Content */}
                <pre className="p-4 bg-[rgba(26,26,46,0.95)] text-sm font-mono text-gray-300 overflow-x-auto leading-relaxed">
                  {output.split('\n').map((line, i) => (
                    <div key={i} className="flex">
                      <span className="inline-block w-6 text-right mr-4 text-gray-600 text-xs select-none shrink-0 leading-relaxed">
                        {i + 1}
                      </span>
                      <span className={line.startsWith('#') ? 'text-gray-500 italic' : 'text-green-400'}>
                        {line}
                      </span>
                    </div>
                  ))}
                </pre>
              </div>

              <p className="text-xs text-gray-500 mt-3">
                Upload this file to <code className="text-primary-300">{domain.trim().replace(/^https?:\/\//, '').replace(/\/.*$/, '')}/ads.txt</code> on your web server.
              </p>
            </motion.div>
          )}
        </div>
      </motion.div>
    </section>
  );
}
